[package]
name = "mpl-candy-guard"
version = "1.0.2"
description = "Metaplex Candy Guard: programmatic access control for Candy Machine."
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/mpl-candy-machine"
license-file = "../../../LICENSE"
edition = "2021"
readme = "../README.md"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-bpf = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.27.0"
arrayref = "0.3.6"
mpl-candy-guard-derive = { path = "../macro", version = "0.2.0" }
mpl-candy-machine-core = { path = "../../candy-machine-core/program", version = "1.0.2", features = ["cpi"] }
mpl-token-metadata = { version = "1.9.0", features = ["no-entrypoint"] }
mpl-token-auth-rules = { version = "1.2.0", features = ["no-entrypoint"] }
solana-program = "~1.14.14"
spl-associated-token-account = { version = "1.1.1", features = ["no-entrypoint"] }
spl-token = { version = "3.3.1", features = ["no-entrypoint"] }
solana-gateway = "0.2.2"
