name: Build Programs

on:
  workflow_call:
    inputs:
      rust:
        default: ${{ env.RUST_VERSION }}
        type: string
      solana:
        default: ${{ env.SOLANA_VERSION }}
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: ${{ env.RUST_VERSION }}
        required: true
        type: string
      solana:
        description: Solana version
        default: ${{ env.SOLANA_VERSION }}
        required: true
        type: string

env:
  CACHE: true
  CARGO_TERM_COLOR: always
  NODE_VERSION: 16.x
  PROGRAMS: '["candy-machine-core", "candy-guard"]'
  RUST_VERSION: 1.65.0
  SOLANA_VERSION: 1.14.13

jobs:
  build_programs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: metaplex-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust }}

      - name: Install Solana
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: ${{ inputs.solana }}
          cache: ${{ env.CACHE }}

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: metaplex-foundation/actions/cache-programs@v1

      - name: Build programs
        env:
          PROGRAMS: ${{ env.PROGRAMS }}
        run: |
          for program in $(echo $PROGRAMS | jq -c '.[]' | sed 's/"//g'); do
            (cd ./programs/$program; cargo build-bpf)
          done

      - name: Upload program builds
        uses: actions/upload-artifact@v3
        with:
          name: program-builds
          # First wildcard ensures exported paths are consistently under the programs folder.
          path: ./program*/**/target/deploy/*.so
          if-no-files-found: error
